---
title: Mapping with Cartopy in Python
image: "/images/post/carto.svg"
author: Masumbuko Semba
date: '2019-12-23'
slug: mapping-with-cartopy-in-python
categories: []
tags:
  - data science
  - mapping
  - Masumbuko Semba
  - cartopy
editor_options: 
  chunk_output_type: console
---

Today we will learn about Cartopy, one of the most common packages for making maps within python, Another popular and powerful library is Basemap; however, Basemap is going away and being replaced with Cartopy in the near future, For this reason, investing your time in learning mapping in python with Cartopy module is recommended.

We thank [Research in Computing Earth Sciences](https://rabernat.github.io/research_computing_2018/maps-with-cartopy.html) because most of material in this post are gleaned from their website. I also thank Phil Elson, a developer of Cartopy and created excellent [Cartopy Tutorial](https://github.com/SciTools/cartopy-tutorial)

Cartopy makes use of the powerful `PROJ.4`, `numpy` and `shapely` libraries and includes a programatic interface built on top of **Matplotlib** for the creation of publication quality maps. Key features of cartopy are its object oriented projection definitions, and its ability to transform points, lines, vectors, polygons and images between those projections.

## Cartopy Projections and other reference systems
In Cartopy, each projection is a class. Most classes of projection can be configured in projection-specific ways, although Cartopy takes an opinionated stance on sensible defaults. Let's create a Plate Carree projection instance.To do so, we need cartopy's crs module. This is typically imported as ccrs (Cartopy Coordinate Reference Systems).

Before we import the modules we need for mapping, we first have to initialize the linkage of python in Rstudio using the **reticulate** package and also set the environment in which the seesion will fetch python functions and package. You must load the reticulate package and set the enviroment while in R chunk;

```{r}
require(reticulate)
use_python("c:/Python/Anaconda3/")

```

We then import some Python's modules using the `import` function. Make sure that you insert the Pyhon chunk for you to load these modules
```{python}

import numpy as np
import pandas as pd
import cartopy.crs as ccrs
import cartopy
import matplotlib.pyplot as plt

```

We can access the Mollweide projection with the code chunk below;
```{python}
ccrs.Mollweide()
```

## Drawing a map
Cartopy optionally depends upon **matplotlib**, and each projection knows how to create a matplotlib Axes (or AxesSubplot) that can represent itself.

The Axes that the projection creates is a cartopy.mpl.geoaxes.GeoAxes. This Axes subclass overrides some of matplotlib's existing methods, and adds a number of extremely useful ones for drawing maps.

We'll go back and look at those methods shortly, but first, let's actually see the cartopy+matplotlib dance in action:

```{python}
import matplotlib.pyplot as plt

plt.axes(projection=ccrs.PlateCarree())
plt.show()
```

That was a little underwhelming, but we can see that the Axes created is indeed one of those GeoAxes[Subplot] instances.

One of the most useful methods that this class adds on top of the standard matplotlib Axes class is the coastlines method. With no arguments, it will add the Natural Earth 1:110,000,000 scale coastline data to the map.

```{python}

plt.figure()
ax = plt.axes(projection=ccrs.PlateCarree())
ax.coastlines()
plt.show()

```

We could just as equally created a matplotlib subplot with one of the many approaches that exist. For example, the plt.subplots function could be used:

```{python}

fig, ax = plt.subplots(subplot_kw={'projection': ccrs.PlateCarree()})
ax.coastlines()
plt.show
```


Projection classes have options we can use to customize the map so that Africa is at the center
```{python}
ax = plt.axes(projection=ccrs.PlateCarree(central_longitude=0))
ax.coastlines()
plt.show()
```

## Useful methods of a GeoAxes
The cartopy.mpl.geoaxes.GeoAxes class adds a number of useful methods. Let's take a look at:

i. `set_global` - zoom the map out as much as possible
i. `set_extent` - zoom the map to the given bounding box
i. `gridlines` - add a graticule (and optionally labels) to the axes
i. `coastlines` - add Natural Earth coastlines to the axes
i. `stock_img` - add a low-resolution Natural Earth background image to the axes
i. `imshow` - add an image (numpy array) to the axes
i. `add_geometries` - add a collection of geometries (Shapely) to the axes

Some More Examples of Different Global Projections

```{python}

projections = [ccrs.PlateCarree(),
               ccrs.Robinson(),
               ccrs.Mercator(),
               ccrs.Orthographic(),
               ccrs.InterruptedGoodeHomolosine()
              ]


for proj in projections:
    plt.figure()
    ax = plt.axes(projection=proj)
    ax.stock_img()
    ax.coastlines()
    ax.set_title(f'{type(proj)}')
    plt.show()

```


## Regional Maps
To create a regional map, we use the `set_extent` method of GeoAxis to limit the size of the region.

```{python, eval=FALSE}
central_lon =43, central_lat = -8.5
extent = [35, 50, -16.5, 0]
ax = plt.axes(projection=ccrs.PlateCarree(central_lon, central_lat))
ax.set_extent(extent)
ax.gridlines()
ax.coastlines(resolution='50m')
plt.show()

```

## Adding Features to the Map
To give our map more styles and details, we add cartopy.feature objects. Many useful features are built in. These "default features" are at coarse (110m) resolution.

i. `cartopy.feature.BORDERS`	Country boundaries
i. `cartopy.feature.COASTLINE`	Coastline, including major islands
`cartopy.feature.LAKES`	Natural and artificial lakes
i. `cartopy.feature.LAND`	Land polygons, including major islands
i. `cartopy.feature.OCEAN`	Ocean polygons
i. `cartopy.feature.RIVERS`	Single-line drainages, including lake centerlines
i. `cartopy.feature.STATES`	(limited to the United States at this scale)

```{python}
import cartopy.feature as cfeature
import numpy as np

central_lat = 37.5
central_lon = -96
extent = [28, 45, -25, 2]
central_lon = np.mean(extent[:2])
central_lat = np.mean(extent[2:])

plt.figure(figsize=(6, 6))
ax = plt.axes(projection=ccrs.EquidistantConic(central_lon, central_lat))
ax.set_extent(extent)

ax.add_feature(cartopy.feature.OCEAN)
ax.add_feature(cartopy.feature.LAND, edgecolor='black')
ax.add_feature(cartopy.feature.LAKES, edgecolor='black')
ax.add_feature(cartopy.feature.RIVERS)
ax.gridlines()
# ax.gridlines(draw_labels=True, xlocs=[32, 36, 40, 44])
plt.show()
```



```{python}
rivers_50m = cfeature.NaturalEarthFeature('physical', 'rivers_lake_centerlines', '10m')

central_lat = 37.5
central_lon = -96
extent = [28, 45, -25, 2]
central_lon = np.mean(extent[:2])
central_lat = np.mean(extent[2:])

plt.figure(figsize=(6, 6))
ax = plt.axes(projection=ccrs.EquidistantConic(central_lon, central_lat))
ax.set_extent(extent)

ax.add_feature(cartopy.feature.OCEAN)
ax.add_feature(cartopy.feature.LAND, edgecolor='black')
ax.add_feature(cartopy.feature.LAKES, edgecolor='black')
ax.add_feature(rivers_50m, facecolor='None', edgecolor='b')
ax.gridlines()
plt.show()
```

## Plotting 2D (Raster) Data
The same principles apply to 2D data. Below we create some example data defined in regular lat / lon coordinates. for this case we will load the global sea surface temperature data. The data is stored as netcdf format and hence we need to load the 

```{python}

import netCDF4 as nc

```

Then we a `Dataset` function from the netCDF4 module to read the file

```{python}
sst = nc.Dataset("e:/MatlabWorking/GHRSST/20150101.nc")
```

We need to extract different variables that are stored in the file. But before we extract them, we must look on the internal structure of the file and identify the variables with correct names. We can do that using the `nc.variables` function
```{python, eval = FALSE}
sst.variables
```

We noticed that the file is the array of `lon`. `lat`, `analysed_sst`, and `time`. The time is the single interval. Then, we extract the variables as the chunk below shows;
```{python}
time = sst.variables['time']
lon = sst.variables['lon']
lat = sst.variables['lat']
data = sst.variables['analysed_sst']

```

Because the data is in the rectangular grid, we also need to convert the `lon` and `lat` to rectangular grid with `np.meshgrid()`. The purpose of meshgrid is to create a rectangular grid out of an array of x values and an array of y values
```{python}

lon2d, lat2d = np.meshgrid(lon, lat)

```

Because the temperature was recorded in Kelvin scale, we can simpy convert to degree by simply substracting with 273
```{python}

datar = data[0,:,:]-273
# datar = np.flipud(datar)
```

Then we can map the spatial distribution of sea surface temperature around the global as shown in figure \@ref(fig:sst)

```{python sst, fig.cap = "Sea surface temperature"}

plt.figure(figsize=(6,5))
ax = plt.axes(projection=ccrs.PlateCarree())
ax.set_global()
# ax.set_extent([-170,170,-30,30])
ax.coastlines()
ax.contourf(lon2d, lat2d, datar, cmap = "jet")
# ax.gridlines()
# ax.gridlines(draw_labels=True, xlocs=[32, 36, 40, 44])
plt.show()

```

